
/* Drop Tables */
drop sequence ph_seq;
DROp TABLE Purchase CASCADE CONSTRAINTS;
CREATE SEQUENCE ph_seq;
SELECT * FROM seq WHERE sequence_name = 'PH_SEQ';
CREATE TABLE Purchase(
	pcid number NOT NULL,
	pcuid varchar2(50) NOT NULL,
	ptotalprice NUMBER  DEFAULT 0,
	pcregdate DATE DEFAULT SYSDATE,
	pcstatus number  DEFAULT 1,
	pcaddress varchar2(100) NOT NULL,
	pcaddressnum number NOT NULL UNIQUE,
	pccontent varchar2(100),
	pccardnum NUMBER NOT NULL,
	pid NUMBER NOT NULL UNIQUE,
	pclpcnt NUMBER NOT NULL,
	pRIMARY KEY (pcid)
);

COMMIT;
SELECT * FROM PURCHASE;


SELECT a.PBRAND, a.PNAME, b.PCLPCNT, b.PCCARDNUM 
FROM PRODUCT a join PURCHASE b
on a.PID =b.PCLPID ;

DELETE PRODUCT,PURCHASE FROM PRODUCT a
INNER JOIN PURCHASE b
ON
a.PID = b.PCLPID
WHERE a.PBRAND, a.PNAME, b.PCLPCNT, b.PCCARDNUM;
	

SELECT b.PCID ,a.PIMAGE ,a.PNAME ,a.PBRAND , b.PCADDRESS ,b.PCADDRESSNUM , b.PTOTALPRICE ,b.PCCONTENT ,b.PCLPCNT,b.PCREGDATE
			FROM PRODUCT a inner join PURCHASE b
			on a.PID =b.PID;
		
SELECT b.PCID ,a.PIMAGE ,a.PNAME ,a.PBRAND , b.PCADDRESS ,b.PCADDRESSNUM , b.PTOTALPRICE ,b.PCCONTENT ,b.PCLPCNT,b.PCREGDATE,b.pcstatus
			FROM PRODUCT a inner join PURCHASE b
			on a.PID =b.PID;
